package.path = package.path .. ";./?.lua"
local helpers = require("helpers")

helpers.nmap("<leader>o", "o<esc>")
helpers.nmap("<leader>O", "O<Esc>")
helpers.nmap("<leader>rr", "viwp")
helpers.nmap("<leader>r;", "@:")
helpers.nmap("<leader>qn", ":cnext<cr>")
helpers.nmap("<leader>qp", ":cprevious<cr>")
helpers.nmap("∆", ":m .+1<cr>==")
helpers.nmap("˚", ":m .-2<cr>==")
helpers.imap("∆", "<esc>:m .+1<cr>==gi")
helpers.imap("˚", "<esc>:m .-2<cr>==gi")
helpers.vmap("∆", ":m '>+1<cr>gv=gv")
helpers.vmap("˚", ":m '<-2<cr>gv=gv")
helpers.nmap("<leader>vd", ":tabdo :Gvdiffsplit")
helpers.nmap([[<leader>']], [["]])
helpers.nmap("<leader>gb", ":Git blame")
