package.path = package.path .. ";../?.lua"

require("elan.plugins.packer")
require("elan.plugins.autopairs")
require("elan.plugins.barbar")
require("elan.plugins.cmp")
require("elan.plugins.comment")
require("elan.plugins.diffview")
require("elan.plugins.fzf")
require("elan.plugins.gitsigns")
require("elan.plugins.lightspeed")
require("elan.plugins.lualine")
require("elan.plugins.nullls")
require("elan.plugins.toggleterm")
require("elan.plugins.tree")
require("elan.plugins.treesitter")
