package.path = package.path .. ";../?.lua"
local h = require("elan.helpers")

h.nmap("<leader>o", "o<esc>")
h.nmap("<leader>O", "O<esc>")
h.nmap("<leader>rr", "viwp")
h.nmap("<leader>r;", "@:")
h.nmap("gn", ":cnext<cr>")
h.nmap("gp", ":cprevious<cr>")
h.nmap("go", ":copen<cr>")
h.nmap("gq", ":cclose<cr>")
-- move lines up and down with alt-k, alt-j
h.nmap("∆", ":m .+1<cr>==")
h.nmap("˚", ":m .-2<cr>==")
h.imap("∆", "<esc>:m .+1<cr>==gi")
h.imap("˚", "<esc>:m .-2<cr>==gi")
h.vmap("∆", ":m '>+1<cr>gv=gv")
h.vmap("˚", ":m '<-2<cr>gv=gv")
h.nmap([[<leader>']], [["]])
h.nmap("<leader>sv", ":source $MYVIMRC<cr>")
h.nmap("<leader>gn", ":q<cr>:q<cr>")
h.nmap("<leader>gb", ":Git blame")
h.nmap("<leader>p", ":Prettier<CR>")
h.vmap("<", "<gv")
h.vmap(">", ">gv")
